### PR TITLE
make multiple changes to database and setup sti for the piece model

### PR DESCRIPTION
**Pull request by mscates**
I made the following changes.
created models for: Pawn, Rook, Bishop, Knight, Queen, King
removed game_id from game model - id is auto created in the table. this was redundant.
removed piece_id from piece model - id is auto created in the table. this was redundant.
renamed user_id_white and user_id_black to user_white_id and user_black_id - naming convention
added user_id and game_id to pieces table for the association to work
removed user_id from users table - redundant
in the game table added belongs_to for user_white and user_black.  
now we can create Pawn, Rook, etc. which inherit the attributes from the piece model

Note:  I have to review this with my mentor on Tuesday, but wanted you guys to have a look at it.

### CODE REVIEW

**Comment by mscates** [comment]
yes, there were a few migrations to complete it all.

**Comment by mscates** [comment]
once i get this merge conflict corrected one more review and we can merge it.

**Comment by JTDeSanto** [comment]
ok, i didn't see a migration for this first commit. i see all the other ones associated with the pieces and user/game id updates

**Comment by mscates** [comment]
It is correct, in this scenario rails adds id to the end of it. If you add
id to the end it will fail

**Pull request merged**
